version: "3"
services:
  web:
    build: .
    ports:
      - "8089:8089"
    environment:
      REDIS_URL: "redis://redis:6379/0"  # Use the hostname of the Redis service
    depends_on:
      - redis
  redis:
    image: "redis:latest"

# Add other services or configurations as needed
